.PHONY: clean All

All:
	@echo "----------Building project:[ A1 - Debug ]----------"
	@"$(MAKE)" -f  "A1.mk"
clean:
	@echo "----------Cleaning project:[ A1 - Debug ]----------"
	@"$(MAKE)" -f  "A1.mk" clean
